### ISSUE TITLE
Sonarr systemd service: Remove --debug argument to mono

### ISSUE THREAD

**Issue by candrews** [xartin/gentoo-overlay#13]
I don't believe the `--debug` argument to `mono` is necessary in Sonarr's systemd service. Can it be removed?

https://github.com/xartin/gentoo-overlay/blob/1d96a8b3284f22e29f9b6a963bbe374227ace3d3/www-apps/sonarr/files/sonarr.service#L10

**Comment by xartin** [comment]
Hi Craig,

There was some mention of or config example references I studied when I was first configuring the ebuild files where the --debug flag had been mentioned as desirable long ago by the sonarr or radarr developers for bug reports. That was i think the only main or major reason I felt it could be advantageous for potential bug report contributions.

I certainly could remove that. I never did manage to figure out how to configure --debug to run with openrc so potentially half of all users using this repo did ever have that debug option enabled.

When sonarr eventually switches to the newer dotnet native binaries radarr uses mono will become unnecessary. Hopefully that development change occurs soon or eventually.

I'll have a look at this as soon as I'm complete the current chore of the week. 

I've been preoccupied with yearly server maintenance that's  involved a full case swap and resilvering a raidz2 volume for the second consecutive day after a disk failure but the finish line is in sight :)

**Comment by candrews** [comment]
Done in the Gentoo repository
