### ISSUE TITLE
Request version bump to Radarr-3.2.0.5048

### ISSUE THREAD

**Issue by j4m35** [xartin/gentoo-overlay#5]
Hi,

Radarr version 3.2.0.5048 was released on 18 May 2021. Requesting a version bump... Thanks!

On a side note, in the ebuild it should have an RDEPEND on "dev-libs/icu", as without it .Net Core will fail to start with a "couldn't find a valid icu package" error.

**Comment by xartin** [comment]
Just wanted to add your version bump request was submitted with outstanding timing. Started a new job this month and was minutes from escaping my desk to go watch a movie :)

New radarr update is available. if there's any issues with the new ebuild post a reply. Enjoy!
