### ISSUE TITLE
Request version bump to Radarr-3.2.1.5070

### ISSUE THREAD

**Issue by j4m35** [xartin/gentoo-overlay#8]
Hi,

Radarr version 3.2.1.5070 was released on 28 May 2021. Requesting a version bump, again... Thanks!

**Comment by xartin** [comment]
Been busy at work the last several weeks and summer fun.

just pushed radarr-3.2.2.5080

Enjoy :)

**Comment by j4m35** [comment]
Thanks @xartin! Hope you had some good summer fun.
