### ISSUE TITLE
Lidarr does not start with OpenRC

### ISSUE THREAD

**Issue by marcoroegner** [xartin/gentoo-overlay#9]
Hi,

Lidarr did not start. I checked /etc/init.d/lidarr and removed ${bin} in line 40 which fixed it for me.

Before: --exec ${bin} ${program} -- \
After: --exec ${program} -- \

Thanks for the overlay!

**Comment by xartin** [comment]
Lidarr previously relied on mono however the dotnet core builds do not.

as a result dependency on mono was depreciated however i missed removing the following from the openrc init template.

```
bin=`which mono`  
--exec ${bin} ${program} -- \

```
Fixed. Thanks for the report and reminder :)
